# PostgreSQL. Versions 9.3 and up are supported.

#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: listtracker
  username: postgres
  password:


test:
  <<: *default
  database: listtracker

production:
  <<: *default
  database: listtracker
  username: postgres
  password: <%= ENV['TODOLIST_DATABASE_PASSWORD'] %>
